### ISSUE TITLE
RSS news and events

### ISSUE THREAD

**Issue by mhadji05** [dylanbrams/UnityRSSReader#1]
Dear Dylan.
Thanks for your tutorial.
I m trying to use your demo but I fail.
I want to present some news and events from a website but it doesn't work. Your code works only for your website.
Can you please explain me how can I modify this code to present the news from this website. (http://www.aradippou.org.cy/index.php/en/news)?
Also can you tell me how can I present image from a website in Unity.

Thanks in advance.

**Comment by dylanbrams** [comment]
You need an RSS feed, rather than a regular website. It's not an HTTP format, it's an RSS format.

http://rss.slashdot.org/Slashdot/slashdotMain

Presenting an image from a website in Unity requires an HTTP get, I think. I haven't done a lot of them, but here's the Unity reference for that.

https://docs.unity3d.com/ScriptReference/Networking.UnityWebRequest.Get.html

**Comment by mhadji05** [comment]
How can I create a RSSfeed. Can you make an explained tutorial? Do you have any idea how can i get the content of the website above and present it into Unity?

Thanks in advance.

**Comment by dylanbrams** [comment]
So, most modern Content Management Systems have an RSS feed built into them. I looked at the source code of that page, and I don't know what CMS is being used. It looks like you're using Node packages or a Java-based plugin system. 
Using Node, I would look into: https://www.npmjs.com/package/rss
Using Java, I'd look into this package (I guess) https://www.vogella.com/tutorials/RSSFeed/article.html

I'm going to close this issue; it's not related to my tool, sadly. It's about your source not actually being an RSS feed. If you want any more help let me know in my Discord.
